export const terms = [
  {
    title: 'There are other terms that may apply to you',
    paragraph: [
      'These terms of use refer to the following additional terms, which also apply to your use of our site:',
    ],
    list: [
      'Our Privacy Policy.  See further under How we may use your personal information.',
      'Our Complaints Policy. See further under Complaints Policy',
    ],
  },
  {
    title: 'We may make changes to these terms',
    paragraph: [
      'We amend these terms from time to time. Every time you wish to use our site, please check these terms to ensure you understand the terms that apply at that time.',
    ],
  },
  {
    title: 'We may make changes to our site',
    paragraph: [
      "We may update and change our site from time to time to reflect changes to our products, our services, our users' needs and our business priorities.",
    ],
  },
  {
    title: 'We may suspend or withdraw our site ',
    paragraph: [
      'Our site is made available free of charge. We do not guarantee that our site, or any content on it, will always be available or be uninterrupted. We may suspend or withdraw or restrict the availability of all or any part of our site for business and operational reasons. We will try to give you reasonable notice of any suspension or withdrawal.',
      'You are also responsible for ensuring that all persons who access our site through your internet connection are aware of these terms of use and other applicable terms and conditions, and that they comply with them.',
    ],
  },
  {
    title: 'We may transfer this agreement to someone else ',
    paragraph: [
      'We may transfer our rights and obligations under these terms to another organisation. We will always tell you in writing if this happens and we will ensure that the transfer will not affect your rights under the contract.',
    ],
  },
  {
    title: 'Our site is only for users in the USA ',
    paragraph: [
      'Our site is directed to people residing in the United States. We do not represent that content available on or through our site is appropriate for use or available in other locations.',
    ],
  },
  {
    title: 'You must keep your account details safe ',
    paragraph: [
      'If you choose, or you are provided with, a user identification code, password or any other piece of information as part of our security procedures, you must treat such information as confidential. You must not disclose it to any third party. We have the right to disable any user identification code or password, whether chosen by you or allocated by us, at any time, if in our reasonable opinion you have failed to comply with any of the provisions of these terms of use. If you know or suspect that anyone other than you knows your user identification code or password, you must promptly notify us at info@manisland.com.',
    ],
  },
  {
    title: 'How you may use material on our site ',
    paragraph: [
      'We are the owner or the licensee of all intellectual property rights in our site, and in the material published on it.  Those works are protected by copyright laws and treaties around the world. All such rights are reserved. You may print off one copy, and may download extracts, of any page(s) from our site for your personal use and you may draw the attention of others within your organisation to content posted on our site. You must not modify the paper or digital copies of any materials you have printed off or downloaded in any way, and you must not use any illustrations, photographs, video or audio sequences or any graphics separately from any accompanying text. Our status (and that of any identified contributors) as the authors of content on our site must always be acknowledged. You must not use any part of the content on our site for commercial purposes without obtaining a licence to do so from us or our  licensors. If you print off, copy or download any part of our site in breach of these terms of use, your right to use our site will cease immediately and you must, at our option, return or destroy any copies of the materials you have made.',
    ],
  },
  {
    title: 'Do not rely on information on this site ',
    paragraph: [
      'The content on our site is provided for general information only. It is not intended to amount to advice on which you should rely. You must obtain professional or specialist advice before taking, or refraining from, any action on the basis of the content on our site. Although we make reasonable efforts to update the information on our site, we make no representations, warranties or guarantees, whether express or implied, that the content on our site is accurate, complete or up to date.',
    ],
  },
  {
    title: 'We are not responsible for websites we link to ',
    paragraph: [
      'Where our site contains links to other sites and resources provided by third parties, these links are provided for your information only. Such links should not be interpreted as approval by us of those linked websites or information you may obtain from them. We have no control over the contents of those sites or resources.',
    ],
  },
  {
    title: 'User-generated content is not approved by us ',
    paragraph: [
      'This website may include information and materials uploaded by other users of the site. This information and these materials have not been verified or approved by us. The views expressed by other users on our site do not represent our views or values.',
    ],
  },
  {
    title: 'How to complain about content uploaded by other users ',
    paragraph: [
      'If you wish to complain about content uploaded by other users, please contact us on info@manisland.com.',
    ],
  },
  {
    title: 'Our responsibility for loss or damage suffered by you  ',
    paragraph: [
      'If you wish to complain about content uploaded by other users, please contact us on info@manisland.com.',
    ],
    сonditions: [
      {
        сondition_title: 'Whether you are a consumer or a business user:',
        сondition_list: [
          'We do not exclude or limit in any way our liability to you where it would be unlawful to do so. This includes liability for death or personal injury caused by our negligence or the negligence of our employees, agents or subcontractors and for fraud or fraudulent misrepresentation.',
          'Different limitations and exclusions of liability will apply to liability arising as a result of the supply of any products or services to you, which will be set out in our Engagement Letter with clients.',
        ],
      },
      {
        сondition_title: 'If you are a business user:',
        сondition_list: [
          'We exclude all implied conditions, warranties, representations or other terms that may apply to our site or any content on it.',
          'We will not be liable to you for any loss or damage, whether in contract, tort (including negligence), breach of statutory duty, or otherwise, even if foreseeable, arising under or in connection with:',
        ],
        condition_sublist: [
          'use of, or inability to use, our site; or',
          'use of or reliance on any content displayed on our site. ',
          'In particular, we will not be liable for: ',
          'loss of profits, sales, business, or revenue; ',
          'business interruption; loss of anticipated savings; ',
          'loss of business opportunity, goodwill or reputation; or ',
          'any indirect or consequential loss or damage.',
        ],
      },
      {
        сondition_title: 'If you are a business user:',
        сondition_list: [
          'Please note that we only provide our site for domestic and private use. You agree not to use our site for any commercial or business purposes, and we have no liability to you for any loss of profit, loss of business, business interruption, or loss of business opportunity. ',
          'If defective digital content that we have supplied, damages a device or digital content belonging to you and this is caused by our failure to use reasonable care and skill, we will either repair the damage or pay you compensation.',
        ],
      },
    ],
  },
  {
    title: 'How we may use your personal information ',
    paragraph: [
      'We will only use your personal information as set out in our Privacy Policy.',
    ],
  },
  {
    title: 'Uploading content to our site ',
    paragraph: [
      'Whenever you make use of a feature that allows you to upload content to our site, or to make contact with other users of our site, you must comply with the terms set out in the “Prohibited uses” below. You warrant that any such contribution does meet those standards, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of warranty. Any content you upload to our site will be considered non-confidential and non-proprietary. You retain all of your ownership rights in your content, but you are required to grant us and other users of our site a limited licence to use, store and copy that content and to distribute and make it available to third parties. We also have the right to disclose your identity to any third party who is claiming that any content posted or uploaded by you to our site constitutes a violation of their intellectual property rights, or of their right to privacy. You are solely responsible for securing and backing up your content. We do not store terrorist content. ',
    ],
  },
  {
    title: 'Rights you are giving us to use material you upload ',
    paragraph: [
      'When you upload or post content to our site, you grant us the following rights to use that content: a worldwide, non-exclusive, royalty-free, transferable licence to use, reproduce, distribute, prepare derivative works of, display, and perform that user-generated content in connection with the service provided by the website and across different media including to promote the site or the service forever; a worldwide, non-exclusive, royalty-free, transferable licence for other users, partners or advertisers to use the content in accordance with the functionality of the site forever.',
    ],
  },
  {
    title:
      'We are not responsible for viruses and you must not introduce them ',
    paragraph: [
      'We do not guarantee that our site will be secure or free from bugs or viruses. You are responsible for configuring your information technology, computer programmes and platform to access our site. You should use your own virus protection software. You must not misuse our site by knowingly introducing viruses, trojans, worms, logic bombs or other material that is malicious or technologically harmful. You must not attempt to gain unauthorised access to our site, the server on which our site is stored or any server, computer or database connected to our site. You must not attack our site via a denial-of-service attack or a distributed denial-of service attack.By breaching this provision, you would commit a criminal offence under the Computer Misuse Act 1990. We will report any such breach to the relevant law enforcement authorities and we will co-operate with those authorities by disclosing your identity to them. In the event of such a breach, your right to use our site will cease immediately.',
    ],
  },
  {
    title: 'Rules about linking to our site ',
    paragraph: [
      'You may link to our homepage, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it. You must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists. You must not establish a link to our site in any website that is not owned by you. Our site must not be framed on any other site, nor may you create a link to any part of our site other than the home page. We reserve the right to withdraw linking permission without notice. If you wish to link to or make any use of content on our site other than that set out above,please contact info@manisland.com.',
    ],
  },
  {
    title: 'Our trade marks ',
    paragraph: [
      'Manhattan VC Holding containers are trademarks of Manhattan VC Holding LLC. You are not permitted to use them without our approval, unless they are part of material you are using as expressly permitted by us.',
    ],
  },
  {
    title: 'Prohibited uses ',
    paragraph: [
      'You may use our site only for lawful purposes.  You may not use our site: ',
    ],
    list: [
      'In any way that breaches any applicable local, national or international law or regulation.',
      'In any way that is unlawful or fraudulent or has any unlawful or fraudulent purpose or effect.',
      'For the purpose of harming or attempting to harm minors in any way.',
      'To bully, insult, intimidate or humiliate any person.',
      'To send, knowingly receive, upload, download, use or re-use any material unless expressly permitted (e.g. by signing our engagement letter).',
      'To transmit, or procure the sending of, any unsolicited or unauthorised advertising or promotional material or any other form of similar solicitation (spam).',
      'To knowingly transmit any data, send or upload any material that contains viruses, Trojan horses, worms, time-bombs, keystroke loggers, spyware, adware or any other harmful programs or similar computer code designed to adversely affect the operation of any computer software or hardware.',
      'Not to reproduce, duplicate, copy or re-sell any part of our site in contravention of these terms of website use.',
      'Not to access without authority, interfere with, damage or disrupt:',
    ],
    sublist: [
      'any part of our site;',
      'any equipment or network on which our site is stored;',
      'any software used in the provision of our site; or',
      'any equipment or network or software owned or used by any third party.',
      'use of or reliance on any content displayed on our site.',
    ],
  },
  {
    title: 'Breach of this policy ',
    paragraph: [
      'When we consider that a breach of these terms has occurred, we may take such action as we deem appropriate. Failure to comply with these terms may result in our taking all or any of the following actions:',
      ,
    ],
    list: [
      'Immediate, temporary or permanent withdrawal of your right to use our site.',
      'Immediate, temporary or permanent removal of any Contribution uploaded by you to our site.',
      'Issue of a warning to you.',
      'Legal proceedings against you for reimbursement of all costs on an indemnity basis (including, but not limited to, reasonable administrative and legal costs) resulting from the breach. ',
      'Further legal action against you. ',
      'Disclosure of such information to law enforcement authorities as we reasonably feel is necessary or as required by law. ',
    ],
    paragraph2: [
      'We exclude our liability for all action we may take in response to breaches of these terms.The actions we may take are not limited to those described above, and we may take any other action we reasonably deem appropriate.',
    ],
  },
  {
    title: 'How this contract can be transferred ',
		paragraph: [
      'We can transfer our rights and obligations under these terms to any third party, provided thisdoes not adversely affect your rights under these terms.',
    ],
  },
  {
    title: 'Which country`s laws apply to any disputes?',
    paragraph: [
      'If you are a consumer,please note that these terms of use, their subject matter and their formation, are governed by US law. You and we both agree that the courts of US, state of New York will have exclusive jurisdiction. If you are a business,these terms of use, their subject matter and their formation (and any non-contractual disputes or claims) are governed by US law. We both agree to the exclusive jurisdiction of the courts of United States.',
    ],
  },



	// {
  //   title: 'There are other terms that may apply to you',
  //   description_list: [
  //     {
	// 			description_list_title: 'description_list_title',
	// 			description_list_text: 'description_list_text',
	// 			description_list_list: [
	// 				{

	// 				},
	// 			]
				
	// 		}
  //   ],
  // },
];

export const countries = [
	{"code":"AF", "name":"Afghanistan"},
	{"code":"AX", "name":"Åland Islands"},
	{"code":"AL", "name":"Albania"},
	{"code":"DZ", "name":"Algeria"},
	{"code":"AS", "name":"American Samoa"},
	{"code":"AD", "name":"Andorra"},
	{"code":"AO", "name":"Angola"},
	{"code":"AI", "name":"Anguilla"},
	{"code":"AQ", "name":"Antarctica"},
	{"code":"AG", "name":"Antigua and Barbuda"},
	{"code":"AR", "name":"Argentina"},
	{"code":"AM", "name":"Armenia"},
	{"code":"AW", "name":"Aruba"},
	{"code":"AU", "name":"Australia"},
	{"code":"AT", "name":"Austria"},
	{"code":"AZ", "name":"Azerbaijan"},
	{"code":"BS", "name":"Bahamas"},
	{"code":"BH", "name":"Bahrain"},
	{"code":"BD", "name":"Bangladesh"},
	{"code":"BB", "name":"Barbados"},
	{"code":"BY", "name":"Belarus"},
	{"code":"BE", "name":"Belgium"},
	{"code":"BZ", "name":"Belize"},
	{"code":"BJ", "name":"Benin"},
	{"code":"BM", "name":"Bermuda"},
	{"code":"BT", "name":"Bhutan"},
	{"code":"BO", "name":"Bolivia, Plurinational State of"},
	{"code":"BQ", "name":"Bonaire, Sint Eustatius and Saba"},
	{"code":"BA", "name":"Bosnia and Herzegovina"},
	{"code":"BW", "name":"Botswana"},
	{"code":"BV", "name":"Bouvet Island"},
	{"code":"BR", "name":"Brazil"},
	{"code":"IO", "name":"British Indian Ocean Territory"},
	{"code":"BN", "name":"Brunei Darussalam"},
	{"code":"BG", "name":"Bulgaria"},
	{"code":"BF", "name":"Burkina Faso"},
	{"code":"BI", "name":"Burundi"},
	{"code":"KH", "name":"Cambodia"},
	{"code":"CM", "name":"Cameroon"},
	{"code":"CA", "name":"Canada"},
	{"code":"CV", "name":"Cape Verde"},
	{"code":"KY", "name":"Cayman Islands"},
	{"code":"CF", "name":"Central African Republic"},
	{"code":"TD", "name":"Chad"},
	{"code":"CL", "name":"Chile"},
	{"code":"CN", "name":"China"},
	{"code":"CX", "name":"Christmas Island"},
	{"code":"CC", "name":"Cocos (Keeling) Islands"},
	{"code":"CO", "name":"Colombia"},
	{"code":"KM", "name":"Comoros"},
	{"code":"CG", "name":"Congo"},
	{"code":"CD", "name":"Congo, the Democratic Republic of the"},
	{"code":"CK", "name":"Cook Islands"},
	{"code":"CR", "name":"Costa Rica"},
	{"code":"CI", "name":"Côte d'Ivoire"},
	{"code":"HR", "name":"Croatia"},
	{"code":"CU", "name":"Cuba"},
	{"code":"CW", "name":"Curaçao"},
	{"code":"CY", "name":"Cyprus"},
	{"code":"CZ", "name":"Czech Republic"},
	{"code":"DK", "name":"Denmark"},
	{"code":"DJ", "name":"Djibouti"},
	{"code":"DM", "name":"Dominica"},
	{"code":"DO", "name":"Dominican Republic"},
	{"code":"EC", "name":"Ecuador"},
	{"code":"EG", "name":"Egypt"},
	{"code":"SV", "name":"El Salvador"},
	{"code":"GQ", "name":"Equatorial Guinea"},
	{"code":"ER", "name":"Eritrea"},
	{"code":"EE", "name":"Estonia"},
	{"code":"ET", "name":"Ethiopia"},
	{"code":"FK", "name":"Falkland Islands (Malvinas)"},
	{"code":"FO", "name":"Faroe Islands"},
	{"code":"FJ", "name":"Fiji"},
	{"code":"FI", "name":"Finland"},
	{"code":"FR", "name":"France"},
	{"code":"GF", "name":"French Guiana"},
	{"code":"PF", "name":"French Polynesia"},
	{"code":"TF", "name":"French Southern Territories"},
	{"code":"GA", "name":"Gabon"},
	{"code":"GM", "name":"Gambia"},
	{"code":"GE", "name":"Georgia"},
	{"code":"DE", "name":"Germany"},
	{"code":"GH", "name":"Ghana"},
	{"code":"GI", "name":"Gibraltar"},
	{"code":"GR", "name":"Greece"},
	{"code":"GL", "name":"Greenland"},
	{"code":"GD", "name":"Grenada"},
	{"code":"GP", "name":"Guadeloupe"},
	{"code":"GU", "name":"Guam"},
	{"code":"GT", "name":"Guatemala"},
	{"code":"GG", "name":"Guernsey"},
	{"code":"GN", "name":"Guinea"},
	{"code":"GW", "name":"Guinea-Bissau"},
	{"code":"GY", "name":"Guyana"},
	{"code":"HT", "name":"Haiti"},
	{"code":"HM", "name":"Heard Island and McDonald Islands"},
	{"code":"VA", "name":"Holy See (Vatican City State)"},
	{"code":"HN", "name":"Honduras"},
	{"code":"HK", "name":"Hong Kong"},
	{"code":"HU", "name":"Hungary"},
	{"code":"IS", "name":"Iceland"},
	{"code":"IN", "name":"India"},
	{"code":"ID", "name":"Indonesia"},
	{"code":"IR", "name":"Iran, Islamic Republic of"},
	{"code":"IQ", "name":"Iraq"},
	{"code":"IE", "name":"Ireland"},
	{"code":"IM", "name":"Isle of Man"},
	{"code":"IL", "name":"Israel"},
	{"code":"IT", "name":"Italy"},
	{"code":"JM", "name":"Jamaica"},
	{"code":"JP", "name":"Japan"},
	{"code":"JE", "name":"Jersey"},
	{"code":"JO", "name":"Jordan"},
	{"code":"KZ", "name":"Kazakhstan"},
	{"code":"KE", "name":"Kenya"},
	{"code":"KI", "name":"Kiribati"},
	{"code":"KP", "name":"Korea, Democratic People's Republic of"},
	{"code":"KR", "name":"Korea, Republic of"},
	{"code":"KW", "name":"Kuwait"},
	{"code":"KG", "name":"Kyrgyzstan"},
	{"code":"LA", "name":"Lao People's Democratic Republic"},
	{"code":"LV", "name":"Latvia"},
	{"code":"LB", "name":"Lebanon"},
	{"code":"LS", "name":"Lesotho"},
	{"code":"LR", "name":"Liberia"},
	{"code":"LY", "name":"Libya"},
	{"code":"LI", "name":"Liechtenstein"},
	{"code":"LT", "name":"Lithuania"},
	{"code":"LU", "name":"Luxembourg"},
	{"code":"MO", "name":"Macao"},
	{"code":"MK", "name":"Macedonia, the former Yugoslav Republic of"},
	{"code":"MG", "name":"Madagascar"},
	{"code":"MW", "name":"Malawi"},
	{"code":"MY", "name":"Malaysia"},
	{"code":"MV", "name":"Maldives"},
	{"code":"ML", "name":"Mali"},
	{"code":"MT", "name":"Malta"},
	{"code":"MH", "name":"Marshall Islands"},
	{"code":"MQ", "name":"Martinique"},
	{"code":"MR", "name":"Mauritania"},
	{"code":"MU", "name":"Mauritius"},
	{"code":"YT", "name":"Mayotte"},
	{"code":"MX", "name":"Mexico"},
	{"code":"FM", "name":"Micronesia, Federated States of"},
	{"code":"MD", "name":"Moldova, Republic of"},
	{"code":"MC", "name":"Monaco"},
	{"code":"MN", "name":"Mongolia"},
	{"code":"ME", "name":"Montenegro"},
	{"code":"MS", "name":"Montserrat"},
	{"code":"MA", "name":"Morocco"},
	{"code":"MZ", "name":"Mozambique"},
	{"code":"MM", "name":"Myanmar"},
	{"code":"NA", "name":"Namibia"},
	{"code":"NR", "name":"Nauru"},
	{"code":"NP", "name":"Nepal"},
	{"code":"NL", "name":"Netherlands"},
	{"code":"NC", "name":"New Caledonia"},
	{"code":"NZ", "name":"New Zealand"},
	{"code":"NI", "name":"Nicaragua"},
	{"code":"NE", "name":"Niger"},
	{"code":"NG", "name":"Nigeria"},
	{"code":"NU", "name":"Niue"},
	{"code":"NF", "name":"Norfolk Island"},
	{"code":"MP", "name":"Northern Mariana Islands"},
	{"code":"NO", "name":"Norway"},
	{"code":"OM", "name":"Oman"},
	{"code":"PK", "name":"Pakistan"},
	{"code":"PW", "name":"Palau"},
	{"code":"PS", "name":"Palestinian Territory, Occupied"},
	{"code":"PA", "name":"Panama"},
	{"code":"PG", "name":"Papua New Guinea"},
	{"code":"PY", "name":"Paraguay"},
	{"code":"PE", "name":"Peru"},
	{"code":"PH", "name":"Philippines"},
	{"code":"PN", "name":"Pitcairn"},
	{"code":"PL", "name":"Poland"},
	{"code":"PT", "name":"Portugal"},
	{"code":"PR", "name":"Puerto Rico"},
	{"code":"QA", "name":"Qatar"},
	{"code":"RE", "name":"Réunion"},
	{"code":"RO", "name":"Romania"},
	{"code":"RU", "name":"Russian Federation"},
	{"code":"RW", "name":"Rwanda"},
	{"code":"BL", "name":"Saint Barthélemy"},
	{"code":"SH", "name":"Saint Helena, Ascension and Tristan da Cunha"},
	{"code":"KN", "name":"Saint Kitts and Nevis"},
	{"code":"LC", "name":"Saint Lucia"},
	{"code":"MF", "name":"Saint Martin (French part)"},
	{"code":"PM", "name":"Saint Pierre and Miquelon"},
	{"code":"VC", "name":"Saint Vincent and the Grenadines"},
	{"code":"WS", "name":"Samoa"},
	{"code":"SM", "name":"San Marino"},
	{"code":"ST", "name":"Sao Tome and Principe"},
	{"code":"SA", "name":"Saudi Arabia"},
	{"code":"SN", "name":"Senegal"},
	{"code":"RS", "name":"Serbia"},
	{"code":"SC", "name":"Seychelles"},
	{"code":"SL", "name":"Sierra Leone"},
	{"code":"SG", "name":"Singapore"},
	{"code":"SX", "name":"Sint Maarten (Dutch part)"},
	{"code":"SK", "name":"Slovakia"},
	{"code":"SI", "name":"Slovenia"},
	{"code":"SB", "name":"Solomon Islands"},
	{"code":"SO", "name":"Somalia"},
	{"code":"ZA", "name":"South Africa"},
	{"code":"GS", "name":"South Georgia and the South Sandwich Islands"},
	{"code":"SS", "name":"South Sudan"},
	{"code":"ES", "name":"Spain"},
	{"code":"LK", "name":"Sri Lanka"},
	{"code":"SD", "name":"Sudan"},
	{"code":"SR", "name":"Suriname"},
	{"code":"SJ", "name":"Svalbard and Jan Mayen"},
	{"code":"SZ", "name":"Swaziland"},
	{"code":"SE", "name":"Sweden"},
	{"code":"CH", "name":"Switzerland"},
	{"code":"SY", "name":"Syrian Arab Republic"},
	{"code":"TW", "name":"Taiwan, Province of China"},
	{"code":"TJ", "name":"Tajikistan"},
	{"code":"TZ", "name":"Tanzania, United Republic of"},
	{"code":"TH", "name":"Thailand"},
	{"code":"TL", "name":"Timor-Leste"},
	{"code":"TG", "name":"Togo"},
	{"code":"TK", "name":"Tokelau"},
	{"code":"TO", "name":"Tonga"},
	{"code":"TT", "name":"Trinidad and Tobago"},
	{"code":"TN", "name":"Tunisia"},
	{"code":"TR", "name":"Turkey"},
	{"code":"TM", "name":"Turkmenistan"},
	{"code":"TC", "name":"Turks and Caicos Islands"},
	{"code":"TV", "name":"Tuvalu"},
	{"code":"UG", "name":"Uganda"},
	{"code":"UA", "name":"Ukraine"},
	{"code":"AE", "name":"United Arab Emirates"},
	{"code":"GB", "name":"United Kingdom"},
	{"code":"US", "name":"United States"},
	{"code":"UM", "name":"United States Minor Outlying Islands"},
	{"code":"UY", "name":"Uruguay"},
	{"code":"UZ", "name":"Uzbekistan"},
	{"code":"VU", "name":"Vanuatu"},
	{"code":"VE", "name":"Venezuela, Bolivarian Republic of"},
	{"code":"VN", "name":"Viet Nam"},
	{"code":"VG", "name":"Virgin Islands, British"},
	{"code":"VI", "name":"Virgin Islands, U.S."},
	{"code":"WF", "name":"Wallis and Futuna"},
	{"code":"EH", "name":"Western Sahara"},
	{"code":"YE", "name":"Yemen"},
	{"code":"ZM", "name":"Zambia"},
	{"code":"ZW", "name":"Zimbabwe"}
]

export const news = [
  {
    id: 1,
    image: 'main_header_bg.png',
    date: '09.01.2022',
    author: 'Dmitriy Bunin',
    title: 'Start a blog to reach your creative peak11111',
    description:
      'CSS-Tricks is created, written by, and maintained by Chris Coyier and a team of swell people. The site is one of...',
  },
  {
    id: 2,
    image: 'main_header_bg.png',
    date: '09.01.2022',
    author: 'Dmitriy Bunin2',
    title: 'Start a blog to reach your creative peak2222',
    description:
      'A weekly email with our favorite articles about design, front-end development, technology, and startups...',
  },
  {
    id: 3,
    image: 'main_header_bg.png',
    date: '09.01.2022',
    author: 'Dmitriy Bunin3',
    title: 'Start a blog to reach your creative peak333',
    description:
      'A weekly email with our favorite articles about design, front-end development, technology, and startups...',
  },
];

export const portfolioItems = [
  {
    id: 1,
    name: 'spacefex',
    title: 'The future of Space Finance',
    founding_date: 'Founded in 2022',
    founding_place: 'USA & Canada',
    tags: [
      'Finance',
      'Information Technologies',
			'Space Science',
			'Space Finance',
    ],
    market_value: '$ 50,000,000.00',
    company_market_cap: '$ 70,12B',
    opened_investmet_opportunities: '$ 50,000,000.00',
    investment_amounts: '$ 50,000,000.00',
  },
  {
    id: 2,
    name: 'teido',
    title: 'The future on onboarding & compliance',
    founding_date: 'Founded in 2018',
    founding_place: 'USA & Canada',
    tags: [
    	'Finance',
      'Information Technologies',
			'Compliance',
			'FinTech'
    ],
    market_value: '$ 42,900,000.00',
    company_market_cap: '$ 100,30B',
    opened_investmet_opportunities: '$ 42,900,000.00',
    investment_amounts: '$ 42,900,000.00',
  },
  {
    id: 3,
    name: 'aqatin',
    title: 'International Payment System for Sport',
    founding_date: 'Founded in 2020',
    founding_place: 'USA & Canada',
    tags: [
      'Finance',
      'Information Technologies',
			'FinTech'
    ],
    market_value: '$ 10,000,000.00',
    company_market_cap: '$ 50,00M',
    opened_investmet_opportunities: '$ 10,000,000.00',
    investment_amounts: '$ 10,000,000.00',
  },
  {
    id: 4,
    name: 'esoque',
    title: 'The competitor of Stripe Atlas',
    founding_date: 'Founded in 2022',
    founding_place: 'USA & Canada',
    tags: [
      'Finance',
      'Information Technologies',
			'Compliance',
			'Startups'
    ],
    market_value: '$ 5,000,000.00',
    company_market_cap: '$ 100.00M',
    opened_investmet_opportunities: '$ 5,000,000.00',
    investment_amounts: '$ 5,000,000.00',
  },
	{
		id: 41,
		name: 'neteast',
		title: 'Asian Payment System',
		founding_date: 'Founded in 2019',
		founding_place: 'USA & Canada',
		tags: [
			'Finance',
			'Information Technologies',
			'FinTech'
		],
		market_value: '$ 6,500,000.00',
		company_market_cap: '$ 26,30M',
		opened_investmet_opportunities: '$ 6,500,000.00',
		investment_amounts: '$ 6,500,000.00',
},
  {
    id: 5,
    name: 'halalcash',
    title: 'First Islamic FinTech Startup',
    founding_date: 'Founded in 2018',
    founding_place: 'USA & Canada',
    tags: [
      'Finance',
      'Information Technologies',
			'FinTech'
    ],
    market_value: '$ 12,000,000.00',
    company_market_cap: '$ 29,30M',
    opened_investmet_opportunities: '$ 12,000,000.00',
    investment_amounts: '$ 12,000,000.00',
  },
	{
		id: 7,
		name: 'blvc',
		title: 'European Car Concierge Broker System',
		founding_date: 'Founded in 2021',
		founding_place: 'USA & Canada',
		tags: [
			'Finance',
			'Information Technologies',
			'Automobiles',
			'FinTech'
		],
		market_value: '$ 4,000,000.00',
		company_market_cap: '$ 15,00M',
		opened_investmet_opportunities: '$ 4,000,000.00',
		investment_amounts: '$ 4,000,000.00',
	},
	{
		id: 71,
		name: 'cnda',
		title: 'Canadian Payment System',
		founding_date: 'Founded in 2021',
		founding_place: 'USA & Canada',
		tags: [
			'Finance',
			'Information Technologies',
			'FinTech'
		],
		market_value: '$ 4,000,000.00',
		company_market_cap: '$ 10,00M',
		opened_investmet_opportunities: '$ 4,000,000.00',
		investment_amounts: '$ 4,000,000.00',
	},
	{
		id: 8,
		name: 'cospay',
		title: 'Cospay Limited',
		founding_date: 'Founded in 2011',
		founding_place: 'USA & Canada',
		tags: [
			'Finance',
			'Information Technologies',
			'FinTech'
		],
		market_value: '$ 65,000,000.00',
		company_market_cap: '$ 500,00M',
		opened_investmet_opportunities: '$ 65,000,000.00',
		investment_amounts: '$ 65,000,000.00',
	},
	{
		id: 9,
		name: 'tyncofex',
		title: 'Tyncofex Limited',
		founding_date: 'Founded in 2018',
		founding_place: 'USA & Canada',
		tags: [
			'Finance',
			'Information Technologies',
			'FinTech'
		],
		market_value: '$ 15,000,000.00',
		company_market_cap: '$ 100,00M',
		opened_investmet_opportunities: '$ 15,000,000.00',
		investment_amounts: '$ 15,000,000.00',
	},
	{
		id: 6,
		name: 'pridepay',
		title: 'Payments for love and peace',
		founding_date: 'Founded in 2020',
		founding_place: 'USA & Canada',
		tags: [
			'Finance',
			'Information Technologies',
			'FinTech'
		],
		market_value: '$ 4,000,000.00',
		company_market_cap: '$ 80,30M',
		opened_investmet_opportunities: '$ 4,000,000.00',
		investment_amounts: '$ 4,000,000.00',
	},

];


export const mock_notifications = [
  {
    type: 'add',
    description: 'John Doe joined team Teido.',
    time: '10:05',
    date: '20.09.2022',
    new_notification: true,
  },
  {
    type: 'add',
    description: 'New application been received. Type: Merchant, Name: Google',
    time: '',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'New application been received. Type: Merchant, Name: Google',
    time: '10:05',
    date: '20.09.2022',
    new_notification: true,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
  {
    type: 'add',
    description: 'T-01: New customer Case has been received',
    time: '10:05',
    date: '20.09.2022',
    new_notification: false,
  },
];